add_library(Bing_Translate MODULE bingtranslate.cpp translatewrapper.cpp network.cpp extensionimpl.cpp)
add_library(Copy_to_Clipboard MODULE copyclipboard.cpp extensionimpl.cpp)
add_library(DeepL_Translate MODULE deepltranslate.cpp translatewrapper.cpp network.cpp extensionimpl.cpp)
add_library(DevTools_DeepL_Translate MODULE devtoolsdeepltranslate.cpp devtools.cpp translatewrapper.cpp network.cpp extensionimpl.cpp)
add_library(DevTools_Papago_Translate MODULE devtoolspapagotranslate.cpp devtools.cpp translatewrapper.cpp network.cpp extensionimpl.cpp)
add_library(DevTools_Systran_Translate MODULE devtoolssystrantranslate.cpp devtools.cpp translatewrapper.cpp network.cpp extensionimpl.cpp)
add_library(Extra_Newlines MODULE extranewlines.cpp extensionimpl.cpp)
add_library(Extra_Window MODULE extrawindow.cpp extensionimpl.cpp)
add_library(Google_Translate MODULE googletranslate.cpp devtools.cpp translatewrapper.cpp network.cpp extensionimpl.cpp)
add_library(Lua MODULE lua.cpp extensionimpl.cpp)
add_library(Regex_Filter MODULE regexfilter.cpp extensionimpl.cpp)
add_library(Regex_Replacer MODULE regexreplacer.cpp extensionimpl.cpp)
add_library(Remove_Repeated_Characters MODULE removerepeatchar.cpp extensionimpl.cpp)
add_library(Remove_Repeated_Phrases MODULE removerepeatphrase.cpp extensionimpl.cpp)
add_library(Remove_Repeated_Phrases_2 MODULE removerepeatphrase2.cpp extensionimpl.cpp)
add_library(Remove_30_Repeated_Sentences MODULE removerepeatsentence.cpp extensionimpl.cpp)
add_library(Replacer MODULE replacer.cpp extensionimpl.cpp)
add_library(Styler MODULE styler.cpp extensionimpl.cpp)
add_library(Thread_Linker MODULE threadlinker.cpp extensionimpl.cpp)

target_precompile_headers(Bing_Translate REUSE_FROM pch)
target_precompile_headers(Copy_to_Clipboard REUSE_FROM pch)
target_precompile_headers(DeepL_Translate REUSE_FROM pch)
target_precompile_headers(DevTools_DeepL_Translate REUSE_FROM pch)
target_precompile_headers(DevTools_Papago_Translate REUSE_FROM pch)
target_precompile_headers(DevTools_Systran_Translate REUSE_FROM pch)
target_precompile_headers(Extra_Newlines REUSE_FROM pch)
target_precompile_headers(Extra_Window REUSE_FROM pch)
target_precompile_headers(Google_Translate REUSE_FROM pch)
target_precompile_headers(Lua REUSE_FROM pch)
target_precompile_headers(Regex_Filter REUSE_FROM pch)
target_precompile_headers(Regex_Replacer REUSE_FROM pch)
target_precompile_headers(Remove_Repeated_Characters REUSE_FROM pch)
target_precompile_headers(Remove_Repeated_Phrases REUSE_FROM pch)
target_precompile_headers(Remove_Repeated_Phrases_2 REUSE_FROM pch)
target_precompile_headers(Remove_30_Repeated_Sentences REUSE_FROM pch)
target_precompile_headers(Replacer REUSE_FROM pch)
target_precompile_headers(Styler REUSE_FROM pch)
target_precompile_headers(Thread_Linker REUSE_FROM pch)

target_link_libraries(Bing_Translate winhttp Qt5::Widgets)
target_link_libraries(DeepL_Translate winhttp Qt5::Widgets)
target_link_libraries(DevTools_DeepL_Translate shell32 winhttp Qt5::Widgets Qt5::WebSockets)
target_link_libraries(DevTools_Papago_Translate shell32 winhttp Qt5::Widgets Qt5::WebSockets)
target_link_libraries(DevTools_Systran_Translate shell32 winhttp Qt5::Widgets Qt5::WebSockets)
target_link_libraries(Extra_Window Qt5::Widgets)
target_link_libraries(Google_Translate shell32 winhttp Qt5::Widgets Qt5::WebSockets)
target_link_libraries(Lua lua53 Qt5::Widgets)
target_link_libraries(Regex_Filter Qt5::Widgets)
target_link_libraries(Styler Qt5::Widgets)
target_link_libraries(Thread_Linker Qt5::Widgets)

set_target_properties(Bing_Translate PROPERTIES OUTPUT_NAME "Bing Translate")
set_target_properties(Copy_to_Clipboard PROPERTIES OUTPUT_NAME "Copy to Clipboard")
set_target_properties(DeepL_Translate PROPERTIES OUTPUT_NAME "DeepL Translate")
set_target_properties(DevTools_DeepL_Translate PROPERTIES OUTPUT_NAME "DevTools DeepL Translate")
set_target_properties(DevTools_Papago_Translate PROPERTIES OUTPUT_NAME "DevTools Papago Translate")
set_target_properties(DevTools_Systran_Translate PROPERTIES OUTPUT_NAME "DevTools Systran Translate")
set_target_properties(Extra_Newlines PROPERTIES OUTPUT_NAME "Extra Newlines")
set_target_properties(Extra_Window PROPERTIES OUTPUT_NAME "Extra Window")
set_target_properties(Google_Translate PROPERTIES OUTPUT_NAME "Google Translate")
set_target_properties(Regex_Filter PROPERTIES OUTPUT_NAME "Regex Filter")
set_target_properties(Regex_Replacer PROPERTIES OUTPUT_NAME "Regex Replacer")
set_target_properties(Remove_Repeated_Characters PROPERTIES OUTPUT_NAME "Remove Repeated Characters")
set_target_properties(Remove_Repeated_Phrases PROPERTIES OUTPUT_NAME "Remove Repeated Phrases")
set_target_properties(Remove_Repeated_Phrases_2 PROPERTIES OUTPUT_NAME "Remove Repeated Phrases 2")
set_target_properties(Remove_30_Repeated_Sentences PROPERTIES OUTPUT_NAME "Remove 30 Repeated Sentences")
set_target_properties(Thread_Linker PROPERTIES OUTPUT_NAME "Thread Linker")

add_custom_target(Cleaner ALL COMMAND del *.xdll WORKING_DIRECTORY ${CMAKE_FINAL_OUTPUT_DIRECTORY})

if (NOT EXISTS ${CMAKE_FINAL_OUTPUT_DIRECTORY}/Qt5WebSockets.dll AND NOT EXISTS ${CMAKE_FINAL_OUTPUT_DIRECTORY}/Qt5WebSocketsd.dll)
    add_custom_command(TARGET DevTools_DeepL_Translate
        POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E remove_directory "${CMAKE_CURRENT_BINARY_DIR}/windeployqt"
        COMMAND set PATH=%PATH%$<SEMICOLON>${qt5_install_prefix}/bin
        COMMAND Qt5::windeployqt --dir ${CMAKE_FINAL_OUTPUT_DIRECTORY} "${CMAKE_FINAL_OUTPUT_DIRECTORY}/DevTools DeepL Translate.dll"
    )
endif() 
